// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRkCblTCY5kEfu7H6LLP2as0DyQmDri0E',
    appId: '1:769712590498:web:3c24d24fdf4ca51c6e91fb',
    messagingSenderId: '769712590498',
    projectId: 'connect-firebasewithflutter',
    authDomain: 'connect-firebasewithflutter.firebaseapp.com',
    storageBucket: 'connect-firebasewithflutter.firebasestorage.app',
    measurementId: 'G-07S5B1BZH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8TO3izxeTl38fGNW4fDmhZE7WjyzVZ8',
    appId: '1:769712590498:android:fe813e029f2a2b186e91fb',
    messagingSenderId: '769712590498',
    projectId: 'connect-firebasewithflutter',
    storageBucket: 'connect-firebasewithflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-PMijtQPu8Mc6p_1BH2FpKL3bAUqShk',
    appId: '1:769712590498:ios:214232d23081b78c6e91fb',
    messagingSenderId: '769712590498',
    projectId: 'connect-firebasewithflutter',
    storageBucket: 'connect-firebasewithflutter.firebasestorage.app',
    iosBundleId: 'com.example.connectFlutterfirebase',
  );

}